apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
        - name: http-echo
          image: http-echo
          imagePullPolicy: Never
          args: ["-listen=:8080", "-text=bar"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  namespace: ingress-nginx
spec:
  selector:
    app: bar
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080