name: Kubernetes Load Test CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write
  
env:
  KIND_VERSION: "v0.20.0"
  K6_VERSION: "v0.48.0"
  CLUSTER_NAME: "load-test"
  REGISTRY_PORT: "5001"
  NS: "ingress-nginx"
  MON_NS: "monitoring"

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          echo "📦 Installing dependencies..."
          curl -Lo kind https://kind.sigs.k8s.io/dl/${{ env.KIND_VERSION }}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
          curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          curl -Lo k6.tar.gz https://github.com/grafana/k6/releases/download/${{ env.K6_VERSION }}/k6-${{ env.K6_VERSION }}-linux-amd64.tar.gz && tar xzf k6.tar.gz --strip-components 1 && sudo mv k6 /usr/local/bin/
          echo "✅ Tools ready"

      - name: Build & Setup Cluster
        run: |
          echo "🐳 Building image..."
          docker build -t localhost:${{ env.REGISTRY_PORT }}/http-echo:latest ./application/http-echo
          docker run -d -p ${{ env.REGISTRY_PORT }}:5000 --name kind-registry registry:2
          
          echo "🎯 Creating cluster..."
          cat > kind-config.yaml <<EOF
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
              extraPortMappings: [{containerPort: 30080, hostPort: 30080}, {containerPort: 30090, hostPort: 30090}]
            - role: worker
            - role: worker
          containerdConfigPatches:
            - |-
              [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${{ env.REGISTRY_PORT }}"]
                endpoint = ["http://kind-registry:5000"]
          EOF
          
          kind create cluster --config=kind-config.yaml --name=${{ env.CLUSTER_NAME }}
          docker network connect kind kind-registry
          docker push localhost:${{ env.REGISTRY_PORT }}/http-echo:latest
          kubectl wait --for=condition=ready nodes --all --timeout=300s
          echo "✅ Cluster ready: $(kubectl get nodes --no-headers | wc -l) nodes"

      - name: Deploy Infrastructure & Apps
        run: |
          echo "🏗️ Deploying..."
          kubectl create ns ${{ env.NS }}
          kubectl apply -f infrastructure_setup/rbac.yaml -f infrastructure_setup/ingress_controller.yaml
          kubectl wait -n ${{ env.NS }} --for=condition=ready pod -l app=ingress-nginx --timeout=300s
          
          helm upgrade --install bar ./application/foo-bar-app -n ${{ env.NS }} --set app.name=bar --set app.responseText=bar --set image.repository=localhost:${{ env.REGISTRY_PORT }}/http-echo --set image.pullPolicy=IfNotPresent --wait
          helm upgrade --install foo ./application/foo-bar-app -n ${{ env.NS }} --set app.name=foo --set app.responseText=foo --set image.repository=localhost:${{ env.REGISTRY_PORT }}/http-echo --set image.pullPolicy=IfNotPresent --wait
          kubectl apply -f infrastructure_setup/ingress.yaml
          echo "✅ Apps deployed"

      - name: Deploy Prometheus
        run: |
          echo "📊 Deploying monitoring..."
          kubectl create ns ${{ env.MON_NS }}
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n ${{ env.MON_NS }} \
            --set prometheus.service.type=NodePort --set prometheus.service.nodePort=30090 \
            --set grafana.enabled=false --set alertmanager.enabled=false \
            --set prometheusOperator.tls.enabled=false --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --wait --timeout=5m
          kubectl wait -n ${{ env.MON_NS }} --for=condition=ready pod -l app.kubernetes.io/name=prometheus --timeout=300s
          echo "✅ Prometheus ready"

      - name: Health Check & Validate
        run: |
          echo "🏥 Validating workloads..."
          for app in ingress-nginx bar foo; do
            kubectl wait -n ${{ env.NS }} --for=condition=ready pod -l app=$app --timeout=300s || exit 1
            echo "✅ $app healthy"
          done
          
          kubectl run test-bar --image=curlimages/curl:latest --rm -i --restart=Never -n ${{ env.NS }} -- curl -sf http://bar.${{ env.NS }}.svc.cluster.local:8080 || exit 1
          kubectl run test-foo --image=curlimages/curl:latest --rm -i --restart=Never -n ${{ env.NS }} -- curl -sf http://foo.${{ env.NS }}.svc.cluster.local:8080 || exit 1
          
          echo "✅ All workloads ready"

      - name: Run Load Test & Capture Metrics
        id: load_test
        run: |
          echo "🚀 Load testing..."
          set +e
          k6 run testing/load-test.js | tee load-test-results.txt
          [ $? -eq 0 ] && echo "STATUS=✅ PASSED" >> $GITHUB_ENV || echo "STATUS=⚠️ FAILED" >> $GITHUB_ENV
          set -e
          
          # Give Prometheus MORE time to collect metrics after test
          echo "⏳ Waiting for Prometheus to collect metrics..."
          sleep 45  # Increased from 15 to 45 seconds
          
          PROM="http://localhost:30090/api/v1/query"
          echo "## Resource Utilization During Load Test" > prom-metrics.txt
          echo "" >> prom-metrics.txt
          
          # CPU usage per pod (using 2m window instead of 5m for faster data)
          echo "### Pod CPU Usage (%)" >> prom-metrics.txt
          curl -s "$PROM?query=rate(container_cpu_usage_seconds_total{namespace=\"${{ env.NS }}\",container!=\"\",container!=\"POD\"}[2m])*100" 2>/dev/null | \
            jq -r '.data.result[]? | "\(.metric.pod): \(.value[1])"' >> prom-metrics.txt 2>/dev/null || echo "No CPU data available yet" >> prom-metrics.txt
          
          echo "" >> prom-metrics.txt
          
          # Memory usage per pod
          echo "### Pod Memory Usage (MB)" >> prom-metrics.txt
          curl -s "$PROM?query=container_memory_working_set_bytes{namespace=\"${{ env.NS }}\",container!=\"\",container!=\"POD\"}/1024/1024" 2>/dev/null | \
            jq -r '.data.result[]? | "\(.metric.pod): \(.value[1])"' >> prom-metrics.txt 2>/dev/null || echo "No memory data available yet" >> prom-metrics.txt
          
          echo "" >> prom-metrics.txt
          
          # Network RX (using 2m window)
          echo "### Network RX (KB/s)" >> prom-metrics.txt
          curl -s "$PROM?query=rate(container_network_receive_bytes_total{namespace=\"${{ env.NS }}\"}[2m])/1024" 2>/dev/null | \
            jq -r '.data.result[]? | "\(.metric.pod): \(.value[1])"' >> prom-metrics.txt 2>/dev/null || echo "No network data available yet" >> prom-metrics.txt
          
          echo "" >> prom-metrics.txt
          
          # Node CPU (using 2m window)
          echo "### Cluster CPU Usage (%)" >> prom-metrics.txt
          curl -s "$PROM?query=(1-avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])))*100" 2>/dev/null | \
            jq -r '(.data.result[0]?.value[1] // "N/A") + "%"' >> prom-metrics.txt 2>/dev/null || echo "No cluster CPU data available" >> prom-metrics.txt
          
          echo "" >> prom-metrics.txt
          
          # Fallback: Show pod count at least
          echo "### Active Pods" >> prom-metrics.txt
          kubectl get pods -n ${{ env.NS }} --no-headers | wc -l | xargs -I {} echo "Total pods running: {}" >> prom-metrics.txt
          
          cat prom-metrics.txt
          echo "✅ Metrics collection complete"


      - name: Generate Report & Comment PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const read = f => { try { return fs.readFileSync(f, 'utf8'); } catch { return 'N/A'; } };
            
            // Extract key k6 metrics
            const k6Results = read('load-test-results.txt');
            const k6Summary = k6Results.split('\n').filter(l => 
              l.includes('✓') || l.includes('✗') || 
              l.includes('http_req_duration') || 
              l.includes('http_req_failed') || 
              l.includes('http_reqs') ||
              l.includes('checks')
            ).join('\n');
            
            const promMetrics = read('prom-metrics.txt');
            
            const report = `## ${{ env.STATUS || '⚠️ UNKNOWN' }}
            
            **Workflow:** [Run #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            **Commit:** \`${{ github.event.pull_request.head.sha || github.sha }}\`
            **Branch:** \`${{ github.event.pull_request.head.ref || github.ref_name }}\`
            
            ---
            
            ### 📊 k6 Load Test Results
            
            <details open>
            <summary><b>Performance Metrics</b></summary>
            
            \`\`\`
            ${k6Summary || 'No k6 results available'}
            \`\`\`
            
            </details>
            
            <details>
            <summary><b>Full k6 Output</b></summary>
            
            \`\`\`
            ${k6Results || 'N/A'}
            \`\`\`
            
            </details>
            
            ---
            
            ### 📈 Resource Utilization (Prometheus)
            
            <details>
            <summary><b>Pod & Node Metrics During Load Test</b></summary>
            
            \`\`\`
            ${promMetrics}
            \`\`\`
            
            </details>
            
            ---
            
            ### ✅ Pipeline Summary
            
            | Component | Status |
            |-----------|--------|
            | Multi-node Cluster | ✅ 3 nodes (1 control-plane + 2 workers) |
            | Docker Image Build | ✅ Built from Dockerfile |
            | NGINX Ingress | ✅ Deployed & Healthy |
            | Helm Deployments | ✅ Bar & Foo apps |
            | Health Checks | ✅ All pods ready |
            | Load Testing | ${{ env.STATUS || '⚠️' }} k6 executed |
            | Monitoring | ✅ Prometheus metrics collected |
            
            ---
            
            ### 🎯 Test Configuration
            
            - **Endpoints:** \`bar.localhost:30080\` & \`foo.localhost:30080\`
            - **Load Pattern:** 
              - Ramp-up: 25 users (30s)
              - Sustained: 50 users (1m)
              - Ramp-down: 0 users (20s)
            - **Total Duration:** ~1m 50s
            - **Monitoring:** Prometheus + kube-state-metrics + node-exporter
            
            ---
            
            *🤖 Automated by GitHub Actions • Built with ❤️ using KinD, Helm, k6 & Prometheus*
            `;
            
            if (context.issue?.number) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: report
              });
            } else {
              console.log(report);
              console.log('\n⚠️ No PR context - this was triggered via workflow_dispatch');
            }

      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name ${{ env.CLUSTER_NAME }} 2>/dev/null || true
          docker rm -f kind-registry 2>/dev/null || true
